package com.juls.accesskeymanager.controller;

import com.juls.accesskeymanager.data.models.AccessKeyDetails;
import com.juls.accesskeymanager.exceptions.BadRequestException;
import com.juls.accesskeymanager.services.AccessKeyService;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.net.URI;
import java.util.List;




/**
 * @author JulsBaby
 * This is the controller class for the user, it provides the endpoints for the functions the user or IT-SCHOOL MANAGER CAN PERFORM ON THE APPLCIATION.
 * @apiNote It requires a request mapping of /api/users in order to acces the endpoints and also any person who tries to access an endpoint in this controller reqiures the role of a user.
 */
@Slf4j
@RestController
@RequestMapping("/api/users")
@RequiredArgsConstructor
public class UserController {


    private final AccessKeyService accessKeyService;



    /**
     * The getAllKeys method returns all the access keys generated by a specific email and that is the default endpoint the user is taken when he or she gets authenticated by the system.
     * @param authentication The authentication is of the the interface Authentication which is held in the SecurityContextHolder class. it holds the details of the user who is currently authenticated.
     * @return All the accesskeys generated by a specific user 
     */
    @GetMapping("/all")
    public ResponseEntity<List<AccessKeyDetails>> getAllKeys(Authentication authentication){
        List <AccessKeyDetails> allKeys = this.accessKeyService.getAllKeysByEmail(authentication.getName());
        return ResponseEntity.ok(allKeys);
    }
   
    /**
     * The generateKey method first of checks if the user has an already actived key, if not, a new access key is generated for the user.
     * @param authentication The details of the user who is currently authenticated.
     * @return redirects the user to the allKeys endpoint
     * @throws BadRequestException It throws an BadRequestException when it finds out that the user already has an active key.
     */
   @GetMapping("/generate")
    public ResponseEntity<Void> generateKey(Authentication authentication) throws BadRequestException{
        try {
            String email = authentication.getName();
            this.accessKeyService.generateKey(email);
            HttpHeaders headers = new HttpHeaders();
            URI uri = new URI("/users/all");
            headers.setLocation(uri);
            return new ResponseEntity<>(headers,HttpStatus.CONTINUE);   
        } catch (Exception e) {
            log.error(e.getMessage());            
        }
        return new ResponseEntity<>(HttpStatus.FORBIDDEN);
    }

}
